USE AuthenticationDB

CREATE TABLE TBL_RJ_USER (
    UserId INT IDENTITY(1,1) NOT NULL,
    Name VARCHAR(100) NOT NULL,
	Email VARCHAR(100) NOT NULL,
	Hash NVARCHAR(256) NOT NULL,
	Salt VARBINARY(128) NOT NULL,
    CONSTRAINT PK_TBL_RJ_USER PRIMARY KEY CLUSTERED (UserId ASC),
    CONSTRAINT UK_TBL_RJ_USER UNIQUE (Email)
)


